version: 2

models:
  - name: babylon_bitcoin_finality_providers

    meta:
      blockchain: bitcoin
      sector: restaking
      project: babylon
      contributors: maybeYonas, pyor_xyz

    config:
      tags: ['babylon', 'bitcon']
    description: "json dump of finality providers from babylon api -> 'https://staking-api.babylonlabs.io/v1/finality-providers?pagination_key='"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - btc_pk
    columns:
      - name: active_delegations
        description: "active delegations"
      - name: active_tvl
        description: "active tvl"
      - name: btc_pk
        description: "private key of the finality provider, serves are unique id"
      - name: commission
        description: "% charged by the finality providers on rewards ?"
      - name: details
        description: "description of finality provider"
      - name: identity
        description: "another unique id ?"
      - name: moniker
        description: "name of finality provider"
      - name: security_contact
        description: "email to send 'wen airdrop'"
      - name: website
        description: "website of finality provider"
      - name: total_delegations
        description: "total delegations"
      - name: total_tvl
        description: "total tvl"

  - name: babylon_bitcoin_staking_outputs

    meta:
      blockchain: bitcoin
      sector: restaking
      project: babylon
      contributors: maybeYonas, pyor_xyz

    config:
      tags: ['babylon', 'bitcon']
    description: "all babylon bitcoin staking outputs and their statuses"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - tx_id
    
    columns:
      - name: block_time
        description: ""
      - name: block_height
        description: ""
      - name: tx_id
        description: ""
      - name: value
        description: ""
      - name: address
        description: ""
      - name: type
        description: ""
      - name: version
        description: ""
      - name: staker
        description: ""
      - name: finality_provider
        description: ""
      - name: stakingtime
        description: ""
      - name: index
        description: ""
      - name: finality_provider_name
        description: ""
      - name: unstake_tx_id
        description: ""
      - name: unstake_block_time
        description: ""
      - name: total_btc
        description: ""
      - name: status
        description: ""
      - name: babylon_acceptance
        description: ""
      - name: babylon_status
        description: ""
      - name: script_hex
        description: ""